name: "CI Pipeline For Async Fastapi Redis Celery Flower App"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: Log SSH key (base64) and cloud username
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          CLOUD_USERNAME: ${{ secrets.CLOUD_USERNAME }}
        run: |
          echo "SSH_KEY_BASE64=$(echo -n "$SSH_KEY" | base64 -w 0)"
          echo "CLOUD_USERNAME=$CLOUD_USERNAME"
